### PR TITLE
feat: validate API responses

### PR DESCRIPTION
**Pull request by wpf500**
Adds validation to the API responses to ensure we aren't accidentally sending back data that the user doesn't have access to.

This is implemented with an interceptor and validation using class-validator. It optionally allows properties to be marked as admin only.

### Todo
- [x] Handle export endpoints

### CODE REVIEW

**Review by JumpLink — COMMENTED** [review]
Looks good to me except for one question

**Comment by wpf500** [comment]
@JumpLink what is that question? :smile:

**Comment by JumpLink** [comment]
Sorry, here is the question:

Any API key has admin and superadmin roles in `src/models/ApiKey.ts`:

```ts
  get activeRoles(): RoleType[] {
    return ["admin", "superadmin"];
  }
```

As far as I understand, admins can create an ApiKey? Does this mean that in this way an admin can get SuperAdmin rights?

**Comment by wpf500** [comment]
Ah yeah I just found your question in my GitHub notifications, will also reply here :).

That's a good point and I'll downgrade API keys to admin. In practice the API only uses admin privileges at the moment anyway but definitely good to fix this now :+1:

**Comment by wpf500** [comment]
Actually that makes me think that a much cleaner way of implementing this is just to make creating API keys for superadmins only, that way it doesn't need to do some arbitrary check of what the authentication source is

**Comment by JumpLink** [comment]
Or an APIKey is linked to the user and simply always has the same rights as the linked user

**Pull request merged**
